'''
General information
----------

This script provides global variables which should be used.
'''
from pathlib import Path

#######################################################################################################################
# Variables - Do not edit this file!
#######################################################################################################################

# The target sampling rate to which we resample
sampling_rate = 250
# Directory of the raw data
raw_dir = Path("dataset", "raw-data")
# Directory of the segmented data (np files)
np_dir = Path(raw_dir.parent, "np-dataset")
# Names of the used sensors
sensor_names = ['Bvp', 'Eda_E4', 'Tmp', 'Resp', 'Eda_RB', 'Bvp_RB', 'Emg']